{% set name = "pgpy" %}
{% set version = "0.6.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/PGPy-{{ version }}.tar.gz
  sha256: 279c2e353f4c3a319f00bd9bd582456e420f8a3ac6de2b4e9731444746828383

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.5
    - setuptools
    - wheel
  run:
    - cryptography >=2.6
    - pyasn1
    - python >=3.5
    - six >=1.9.0

test:
  imports:
    - pgpy
    - pgpy.packet
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/SecurityInnovation/PGPy
  summary: Pretty Good Privacy for Python
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - declanjscott
